# Generated by Django 3.0.5 on 2021-07-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        ('sizes', '0001_initial'),
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colors.Color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='image id'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sizes.Size', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
