# Generated by Django 3.0.5 on 2021-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='image', upload_to='category/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
