# Generated by Django 3.0.5 on 2021-10-08 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('price', models.FloatField(default=1, verbose_name='price')),
                ('discount_price', models.FloatField(default=0, verbose_name='discount price')),
                ('product_details', models.TextField(verbose_name='priduct details')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='image')),
                ('variant', models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=15, verbose_name='variant')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('on_sale', models.BooleanField(default=False, verbose_name='on sale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_view', models.DateTimeField(blank=True, null=True, verbose_name='last view')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.Category', verbose_name='category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('review', models.TextField(verbose_name='review')),
                ('ip', models.CharField(max_length=30, verbose_name='ip')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='last review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.Product', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
