# Generated by Django 3.0.5 on 2021-08-11 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wished',
            field=models.ManyToManyField(related_name='wished', to=settings.AUTH_USER_MODEL),
        ),
    ]
