# Generated by Django 3.0.5 on 2021-08-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_wished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wished',
        ),
    ]
