# Generated by Django 3.0.5 on 2021-08-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210820_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_view',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last view'),
        ),
    ]
