# Generated by Django 3.0.5 on 2021-08-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='item',
            new_name='product',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(default='ip', max_length=30, verbose_name='ip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='last_review',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last review'),
        ),
    ]
