# Generated by Django 3.0.5 on 2021-08-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_auto_20210811_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.CharField(choices=[('Wish', 'Wish'), ('Unwish', 'Unwish')], default='status', max_length=50, verbose_name='status'),
            preserve_default=False,
        ),
    ]
