# Generated by Django 3.0.5 on 2021-08-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_wishlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='status',
        ),
    ]
