# Generated by Django 3.0.5 on 2021-08-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_auto_20210811_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wished',
            field=models.CharField(choices=[('Wished', 'Wished'), ('Unwished', 'Unwished')], default='wished', max_length=20),
            preserve_default=False,
        ),
    ]
