# Generated by Django 3.2.8 on 2021-10-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='color name')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
            ],
        ),
    ]
