# Generated by Django 3.0.5 on 2021-08-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210812_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='building_address',
        ),
    ]
